// 07-meta-nuxtjs/app/components/CottageCard.vue
<script setup lang="ts">
interface Cottage {
  id: number
  name: string
  description: string
  image: string
  price: number
  location: string
  guests: number
}

defineProps<{
  cottage: Cottage
}>()
</script>

<template>
  <article class="bg-white dark:bg-stone-800 rounded-2xl shadow-lg overflow-hidden group hover:shadow-xl transition-shadow duration-300">
    <div class="relative h-48 overflow-hidden">
      <NuxtImg
        :src="cottage.image"
        :alt="cottage.name"
        class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
        sizes="sm:100vw md:50vw lg:33vw"
      />
    </div>
    <div class="p-6">
      <div class="flex justify-between items-start mb-2">
        <h2 class="text-xl font-semibold text-stone-800 dark:text-stone-100">
          {{ cottage.name }}
        </h2>
        <span class="text-amber-600 font-bold">{{ cottage.price }}€/night</span>
      </div>
      <p class="text-stone-600 dark:text-stone-300 text-sm mb-4">
        {{ cottage.description }}
      </p>
      <div class="flex justify-between items-center text-sm text-stone-500 dark:text-stone-400">
        <span>📍 {{ cottage.location }}</span>
        <span>👥 {{ cottage.guests }} guests</span>
      </div>
      <NuxtLink
        :to="`/cottages/${cottage.id}`"
        class="mt-4 block text-center bg-amber-600 hover:bg-amber-700 text-white font-semibold py-2 px-4 rounded-full transition-colors duration-300"
      >
        View Details
      </NuxtLink>
    </div>
  </article>
</template>

// 07-meta-nextjs/app/(cottages)/cottages/components/CottageCard.tsx
import Image from "next/image";
import Link from "next/link";
import type { CountryCottage } from "@/app/api/cottages/route";

interface CottageCardProps {
  cottage: CountryCottage;
}

export default function CottageCard({ cottage }: Readonly<CottageCardProps>) {
  return (
    <Link
      href={`/cottages/${cottage.id}`}
      className="group block overflow-hidden rounded-2xl bg-white shadow-lg transition-all duration-300 hover:shadow-xl hover:scale-[1.02] dark:bg-stone-800"
    >
      <div className="relative h-52 w-full overflow-hidden">
        <Image
          src={cottage.imageUrl}
          alt={cottage.name}
          fill
          className="object-cover transition-transform duration-500 group-hover:scale-110"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
      </div>
      <div className="p-5">
        <h3 className="text-xl font-semibold text-stone-800 dark:text-stone-100">
          {cottage.name}
        </h3>
        <p className="mt-2 text-sm text-stone-600 dark:text-stone-300 flex items-center gap-1">
          <span>📍</span> {cottage.address}
        </p>
        <p className="mt-1 text-sm text-stone-500 dark:text-stone-400">
          {cottage.country}
        </p>
        <div className="mt-4 flex items-center justify-between pt-4 border-t border-stone-200 dark:border-stone-700">
          <span className="text-2xl font-bold text-amber-600 dark:text-amber-500">
            ${cottage.price.toLocaleString()}
          </span>
          <span className="text-sm text-stone-500 dark:text-stone-400 bg-stone-100 dark:bg-stone-700 px-3 py-1 rounded-full">
            por noche
          </span>
        </div>
      </div>
    </Link>
  );
}
